### ISSUE TITLE
Codec Cannot Encode

### ISSUE THREAD

**Issue by thisguy23** [Th3Hurrican3/PEpper#2]
Ran into this issue. 
![11 py](https://user-images.githubusercontent.com/5863477/61239944-10845700-a70e-11e9-956e-567fad665c58.png)

**Comment by Th3Hurrican3** [comment]
Hi @thisguy23, what's your locale?

**Comment by aszurnasirpal** [comment]
I have the same error on both Kali linux / Tsarugi Linux :
english locale set by:
localectl set-locale LANG=en_US.utf8

**Comment by Th3Hurrican3** [comment]
Does appending 
`# -*- coding: UTF-8 -*-`
at the beginning of the _sections.py_ module_ make it work?

**Comment by thisguy23** [comment]
Not set, this must be an issue with my box closing

**Comment by thisguy23** [comment]
Working now! Thanks, I had to manually edit my /etc/default/locale LANG parameter as the commands were giving errors.
